name: Deploy from Netlify to GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git

      - name: Copy files from Netlify to GitHub repo
        run: |
          git clone https://github.com/username/repo-name.git
          cp -r /path/to/netlify/build/* ./repo-name
          cd repo-name
          git add .
          git commit -m "Automated commit from Netlify"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
